### PR TITLE
Fixes issue #14 by adding support for -C option

### LINKED ISSUE #14: Feature request: add configuration support
## Feature Request

I have noticed that `ririio-ssg` lacks support parsing config files in `.json` format. I would like to contribute to your project so it can successfully accept and process a valid JSON config file. 

Please assign this issue to me.

### PR DESCRIPTION
**Pull request by SerpentBytes**
This PR fixes and closes #14 by adding support for the `-C`  option. 

Users can now pass a `.json` file with keys such as `input`, `output`, and `lang` to override the application's default behaviour.

### CODE REVIEW

**Comment by Ririio** [comment]
The code is outdated, might need to update it to fit the current version of the repository

**Comment by SerpentBytes** [comment]
I will update the code with the changes you made to the `main` branch 3 hours ago.

**Comment by Ririio** [comment]
> 

I also noticed that your "lang" command doesn't affect the current iteration of input. When I change the language to "en-CA", this change only occurs on the next config command-- the current ones will have a value of its previous language i.e., "en-US"

**Comment by SerpentBytes** [comment]
I have updated the code.

The `.env` file was not updating correctly because you are using functions like `readFile` and `writeFile` from the `fs` module instead of using `readFileSync` and `writeFileSync`. Since you are using asynchronous functions, they return immediately while they still function in the background. I have updated your `readFileSync` to stop execution until the values in the `.env` file are overwritten properly.

**Pull request merged**
